[package]
name = "brioche"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.1", features = ["blas"] }
rand = "0.9.2"
burn = { version = "~0.19", features = ["std", "tui", "train", "vision", "wgpu", "fusion", "ndarray"], default-features = false }
anyhow = "1.0.100"
ort = { git = "https://github.com/pykeio/ort.git", features = ["ndarray"] }
burn-import = { version = "~0.19", features = ["pytorch"] }

[dev-dependencies]
ndarray-npy = "0.10.0"
