[package]
name = "brioche"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.1", features = ["blas"] }
rand = "0.9.2"
burn = { version = "~0.19", features = ["std", "train", "vision", "metal", "fusion"], default-features = false }
anyhow = "1.0.100"
ort = "=2.0.0-rc.11"
burn-import = { version = "~0.19", features = ["pytorch"] }

[dev-dependencies]
ndarray-npy = "0.10.0"
